name: writer
description: Article writer with reflection capability
system_template: writer_system
llm_model: haiku-latest
tools:
  - builtins.launch_agent:launch_agent
  - builtins.list_agents:list_agents
  - builtins.finish:finish
