name: counter
description: An agent that counts numbers
system_template: counter_system
llm_model: haiku-latest
tools:
  - increment:increment
  - get_count:get_count
  - builtins.finish:finish
interactive: false
options: {}
