name: creature_socializing
description: Creature in socializing mode - interacting with other creatures
system_template: creature_socializing_system
llm_model: haiku-latest
tools:
  - get_position
  - look
  - move
  - say
  - talk_to
  - speak_to_hugin
  - get_relationships
  - set_behavior_mode
  - remember
  - recall_memories
interactive: false
options:
  behavior_mode: socializing
